doctrine:
    dbal:
        host: 127.0.0.1
        port: 3306
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASS)%'
        dbname: order_manager_dev
        driver: pdo_mysql
        charset: UTF8
        server_version: mariadb-10.3.25

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
