doctrine:
    dbal:
        host: '%env(resolve:DB_HOST)%'
        port: '%env(resolve:DB_PORT)%'
        user: '%env(resolve:DB_USER)%'
        password: '%env(resolve:DB_PASS)%'
        dbname: '%env(resolve:DB_NAME)%'
        driver: '%env(resolve:DB_DRIVER)%'
        charset: '%env(resolve:DB_CHARSET)%'
        server_version: '%env(resolve:DB_SERVER_VERSION)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
