framework:
    set_content_language_from_locale: true
    set_locale_from_accept_language: true
    enabled_locales: ['pl', 'en']
    default_locale: pl
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
