services:

   dev:
      container_name: dev
      build:
         context: ./.docker/dev
      command: symfony server:start
      ports:
         - '8000:8000'
      volumes:
         - .:/var/www/OrderManager
         - ./.docker/dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
         - dev-app-home:/home/app/
      environment:
         PHP_IDE_CONFIG: "serverName=dev"
      networks:
         - order_manager

   db:
      container_name: db
      image: mysql:9.0.0
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: order_manager
      ports:
         - '4306:3306'
      networks:
         - order_manager
      volumes:
         - data-db:/var/lib/mysql

   redis:
      container_name: redis
      image: redis:7.4.0
      ports:
         - '6379:6379'
      networks:
         - order_manager
      volumes:
         - redis:/data

networks:
   order_manager:

volumes:
   data-db:
   dev-app-home:
   redis:
