version: '3.8'

services:
  db:
    container_name: om_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_manager
      MYSQL_USER: order_manager
      MYSQL_PASSWORD: 12345
    ports:
      - '4306:3306'
    volumes:
      - /var/lib/mysql
  php:
    container_name: om_php
    build:
      context: ./.docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/OrderManager
    depends_on:
      - db
  nginx:
    container_name: om_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/OrderManager
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db