services:
   php:
      build:
         context: ./.docker/php
      volumes:
         - .:/var/www/OrderManager
      ports:
         - '8000:8000'
         - '443:443'

   node:
      image: node:20.15.0
      volumes:
         - .:/var/www/OrderManager

   db:
      container_name: om_db
      image: mysql:9.0.0
#      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: order_manager
         MYSQL_USER: order_manager
         MYSQL_PASSWORD: 12345
      ports:
         - '4306:3306'
      networks:
         - order_manager
      volumes:
         - data-db:/var/lib/mysql

#   database:
#      image: postgres:${POSTGRES_VERSION:-16}-alpine
#      environment:
#         POSTGRES_DB: ${POSTGRES_DB:-app}
#         # You should definitely change the password in production
#         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#         POSTGRES_USER: ${POSTGRES_USER:-app}
#      healthcheck:
#         test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}" ]
#         timeout: 5s
#         retries: 5
#         start_period: 60s
#      volumes:
#         - database_data:/var/lib/postgresql/data:rw

networks:
   order_manager:

volumes:
   data-db:
