services:
  _defaults:
    autowire: true

  App\Reports\ReportsFactory:
    arguments:
      $reports:
        - '@App\Reports\CertifiedUaPlReport\CertifiedUaPlReport'
        - '@App\Reports\PerStaffReport\PerStaffReport'
        - '@App\Reports\PerEachStaffReport\PerEachStaffReport'

  App\Reports\CertifiedUaPlReport\CertifiedUaPlReport: ~
  App\Reports\PerStaffReport\PerStaffReport: ~
  App\Reports\PerEachStaffReport\PerEachStaffReport: ~

  App\Reports\PerStaffReport\PerStaffReportForm:
    autoconfigure: true