name: Tests
on: pull_request

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Unit
        run: |
          composer install --no-interaction
          php ~/.composer/vendor/bin/codecept run unit